# Generated by Django 5.1.6 on 2025-07-08 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='matchplayer',
            name='growth_resources',
            field=models.IntegerField(default=2),
        ),
    ]
