# Generated by Django 5.1.6 on 2025-07-11 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0003_matchplayer_accepted_matchplayer_growth_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='korea_nerf',
            field=models.BooleanField(default=False),
        ),
    ]
