# Generated by Django 5.1.6 on 2025-07-16 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0004_match_korea_nerf'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_draft_nations',
            field=models.IntegerField(default=0),
        ),
    ]
