# Generated by Django 5.1.6 on 2025-07-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0007_nationspreferences_symbols'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='card_draw_limits',
            field=models.BooleanField(default=False),
        ),
    ]
