# Generated by Django 5.1.6 on 2025-12-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0013_matchplayer_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='weighted_card_draw',
            field=models.BooleanField(default=False),
        ),
    ]
