# Generated by Django 5.1.6 on 2025-07-18 07:01

import django.db.models.functions.datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0005_match_extra_draft_nations'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='created',
            field=models.DateTimeField(auto_now_add=True, db_default=django.db.models.functions.datetime.Now()),
        ),
        migrations.AddField(
            model_name='match',
            name='new_turn',
            field=models.DateTimeField(db_default=django.db.models.functions.datetime.Now()),
        ),
    ]
