# Generated by Django 5.1.6 on 2025-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0006_match_created_match_new_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='nationspreferences',
            name='symbols',
            field=models.BooleanField(default=False),
        ),
    ]
