# Generated by Django 5.1.6 on 2025-07-25 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0008_match_card_draw_limits'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='last_chat',
            field=models.IntegerField(default=0),
        ),
    ]
