# Generated by Django 5.1.6 on 2025-10-21 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0009_matchplayer_last_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='lincoln_nerf',
            field=models.BooleanField(default=False),
        ),
    ]
