# Generated by Django 5.1.6 on 2025-10-24 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0010_match_lincoln_nerf'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='resource_remainder_tiebreaker',
            field=models.BooleanField(default=False),
        ),
    ]
