# Generated by Django 5.1.6 on 2025-11-01 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0011_match_resource_remainder_tiebreaker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='replay',
            field=models.TextField(blank=True, default=''),
        ),
    ]
