# Generated by Django 5.1.6 on 2025-11-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nations', '0012_alter_match_replay'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchplayer',
            name='notes',
            field=models.CharField(blank=True, default='', max_length=4000),
        ),
    ]
